Onet_App/Controllers/ChangePhoneController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml.Spreadsheet;
using Microsoft.AspNetCore.Mvc;
using Onet_App.Models;
using Onet_App.Models.Services;
using Onet_App.Models.Services.IServices;
using Onet_App.Models.ViewModel;

namespace Onet_App.Controllers
{
    public class ChangePhoneController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Onet_App/Views/ChangePhone/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<section class="header"></section>
<section class="content">
    <div class="col-md-12">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h4> <b>Change Details</b></h4>

            </div>
            <div class="box-body">
                <div class="col-md-3">
                    <div class="form-group">
                        <label>Account No: </label>
                        <input type="text" class="form-control CharcaterTextBox" id="txtptpdate" placeholder="Account Number" readonly="readonly" value="2258965126">
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <label>Account ID: </label>
                        <input type="text" class="form-control CharcaterTextBox" id="txtptpdate" placeholder="Account ID" readonly="readonly" value="25">
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <label>Old Phone No: </label>
                        <input type="text" class="form-control CharcaterTextBox" id="txtptpdate" placeholder="Old Phone No." readonly="readonly" value="9966585533">
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <label>Old Address: </label>
                        <input type="text" class="form-control CharcaterTextBox" id="txtptpdate" placeholder="Old Address" readonly="readonly" value="Noida">
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="box box-default" style="overflow:auto;">
                        <div class="box-header with-border">
                            <span><b>Remark Details</b></span>
                        </div>
                        <div class="box-body">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Remark</th>
                                        <th>Remark by</th>
                                        <th>Remark Date</th>

                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td>
                                            Demo 1
                                        </td>
                                        <td>
                                            Agent
                                        </td>
                                        <td>
                                            @DateTime.Now.ToString("mm/dd/yyyy")
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            Demo 2
                                        </td>
                                        <td>
                                            Supervisior
                                        </td>
                                        <td>
                                            @DateTime.Now.ToString("mm/dd/yyyy")
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

                <div class="col-md-3">
                    <div class="form-group">
                        <label><span style="color: #ff0000;">*</span>New Number: </label>
                        <input type="text" class="form-control CharcaterTextBox" id="txtptpdate" placeholder="New Number">
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <label><span style="color: #ff0000;">*</span>Alternate Number: </label>
                        <input type="text" class="form-control CharcaterTextBox" id="txtptpdate" placeholder="Alternate Number">
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <label><span style="color: #ff0000;">*</span>New Address: </label>
                        <input type="text" class="form-control CharcaterTextBox" id="txtptpdate" placeholder="New Address">
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <label><span style="color: #ff0000;">*</span>Remarks From Skip Tracer: </label>
                        <input type="text" class="form-control CharcaterTextBox" id="txtptpdate" placeholder="Remarks From Skip Tracer">
                    </div>
                </div>
                <div class="box-footer with-border">
                    <div class="pull-right">
                        <input type="button" class="btn btn-primary btn-flat" id="btnAdd" value="UPDATE" />
                        <a asp-controller="ChangePhone" asp-action="Index" class="btn btn-danger btn-flat">Clear</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>