Onet_App/Controllers/CRMController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml.Spreadsheet;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Onet_App.Models;
using Onet_App.Models.Services;
using Onet_App.Models.Services.IServices;
using Onet_App.Models.ViewModel;

namespace Onet_App.Controllers
{
    public class CRMController : Controller
    {
        public IConfiguration Configuration { get; }
        private readonly ApplicationDbContext _db;
        private ICRMServices crm_obj => new CRMServices(_db);
        private IDispositionServices dispositionServices => new DispositionServices(_db);
        private ICampaignServices campaignservices => new CampaignServices(_db);
        private ILeadAssignmentServices leadassignServices => new LeadAssignmentServices(_db);
        private IRemarkServices remark_services => new RemarkServices(_db);
        private IActivityServices activityServices => new ActivityServices(_db);
        private IManualAssignmentService manualAssignmentService => new ManualAssignmentService(_db);
        public CRMController(ApplicationDbContext db, IConfiguration configuration)
        {
            _db = db;
            Configuration = configuration;
        }

        [HttpGet]
        public IActionResult Index(string mobile, bool isautomate)
        {
            UserVM _userModel = HttpContext.Session.GetObjectFromJson<UserVM>(RoleType.QA);
            if (_userModel != null)
            {
                CRMVM CrmVM = new CRMVM();
                StringBuilder str = new StringBuilder();

                CrmVM.isautomate = isautomate;
                CrmVM.dispositionModels = dispositionServices.GetAllParentDisposition();

                if (_userModel.campaign_id > 0)
                {
                    CrmVM.campaign_name = _db.campaigns.FirstOrDefault(x => x.campaign_id == _userModel.campaign_id).campaign_name;
                    if (CrmVM.campaign_name.ToLower().Trim() == Configuration.GetConnectionString("Campaign").ToLower().Trim())
                    {
                        CrmVM.EndorserModelList = _db.endorsers.ToList();
                    }
                    else
                    {
                        CrmVM.EndorserModelList = _db.endorsers.Where(x => x.campaign_id == _userModel.campaign_id).ToList();
                    }
                }
                CrmVM.EndorserModelList.Insert(0, new EndorserModel { id = 0, endorser_name = "--Select--" });
                #region Balance for Collection
                CrmVM.balanceForCollectionModels = crm_obj.GetAllBalanceForCollection();
                CrmVM.balanceForCollectionModels.Insert(0, new BalanceForCollectionModel { id = 0, balance_collection_name = "--Select--" });
                #endregion
                CrmVM.campaign_id = _userModel.campaign_id;
                CrmVM.cityModels = crm_obj.GetAllCity();
                CrmVM.cityModels.Insert(0, new CityModel { city_id = 0, city_name = "--Select--" });
                CrmVM.modeOfSettlementModels = crm_obj.GetAllModeOfSettlement();
                CrmVM.modeOfSettlementModels.Insert(0, new ModeOfSettlementModel { id = 0, modeofsettlement_name = "--Select--" });
                CrmVM.paymentChannelModels = crm_obj.GetAllPayementChannel();
                CrmVM.paymentChannelModels.Insert(0, new PaymentChannelModel { id = 0, payment_channel_name = "--Select--" });
                CrmVM.reasonForNonPaymentModels = crm_obj.GetAllReasonForNonPayment();
                CrmVM.reasonForNonPaymentModels.Insert(0, new ReasonForNonPaymentModel { id = 0, reason_for_non_payment_name = "--Select--" });
                CrmVM.regionModel = crm_obj.GetAllRegion();
                CrmVM.regionModel.Insert(0, new RegionModel { id = 0, region_name = "--Select--" });
                CrmVM.skipTraceModels = crm_obj.GetAllSkipTrace();
                CrmVM.skipTraceModels.Insert(0, new SkipTraceModel { id = 0, skip_trace_name = "--Select--" });
                CrmVM.statusModels = crm_obj.GetAllStatus();
                CrmVM.statusModels.Insert(0, new StatusModel { id = 0, status_name = "--Select--" });

                if (!String.IsNullOrWhiteSpace(mobile))
                {
                    CRMModel Data = new CRMModel();
                    if (_userModel.role_name_text == RoleType.Agent)
                    {
                        Data = crm_obj.GetCrmByMobileNoAndCamp(mobile, _userModel.campaign_id);
                    }
                    else
                    {
                        Data = crm_obj.GetCrmByMobileNo(mobile);
                    }

                    if (Data != null)
                    {
                        CrmVM.OnetId = "Onet" + Data.crm_id.ToString();
                        CrmVM.crm_id = Data.crm_id;
                        CrmVM.account_name = Data.account_name;
                        CrmVM.account_no = Data.account_no;
                        CrmVM.address = Data.address;
                        CrmVM.agent_id = Data.agent_id;
                        CrmVM.age_group = Data.age_group;
                        CrmVM.amount_collected = Data.amount_collected;
                        CrmVM.authorized_representatives = Data.authorized_representatives;
                        CrmVM.balance_for_collection = Data.balance_for_collection;
                        CrmVM.company_name = Data.company_name;
                        CrmVM.phone1 = Data.phone1;
                        CrmVM.count_of_attempted_contact_numbers = Data.count_of_attempted_contact_numbers;
                        CrmVM.createdby = Data.createdby;
                        CrmVM.date_invoice = Data.date_invoice.HasValue == true ? Data.date_invoice : (DateTime?)null;
                        CrmVM.email = Data.email;
                        CrmVM.financial_contact_person = Data.financial_contact_person;
                        CrmVM.give_new_contact_no = Data.give_new_contact_no;
                        CrmVM.invoice_amount = Data.invoice_amount;
                        CrmVM.invoice_no = Data.invoice_no;
                        CrmVM.mode_of_settlement = Data.mode_of_settlement;
                        CrmVM.number_of_accounts = Data.number_of_accounts;
                        CrmVM.outstanding_balance = Data.outstanding_balance;
                        CrmVM.overdue_balance = Data.overdue_balance;
                        CrmVM.payment_channel = Data.payment_channel;
                        CrmVM.phone2 = Data.phone2;
                        CrmVM.phone3 = Data.phone3;
                        CrmVM.phone4 = Data.phone4;
                        CrmVM.ptp_amount = Data.ptp_amount;
                        CrmVM.ptp_date = Data.ptp_date.HasValue == true ? Data.ptp_date : (DateTime?)null;
                        CrmVM.ptp_dated_by = Data.ptp_dated_by;
                        CrmVM.recommendation = Data.recommendation;
                        CrmVM.region_primary = Data.region_primary;
                        CrmVM.region_secondary = Data.region_secondary;
                        CrmVM.city = Data.city;
                        CrmVM.service_id_no = Data.service_id_no;
                        CrmVM.service_type = Data.service_type;
                        CrmVM.skip_trace = Data.skip_trace;
                        CrmVM.skip_trace_child = Data.skip_trace_child;
                        CrmVM.status = Data.status;
                        CrmVM.supervisor_id = Data.supervisor_id;
                        CrmVM.remarklist = remark_services.GetRemarkByLeadId(CrmVM.crm_id);
                        CrmVM.activityHistoryList = activityServices.GetActivityByLeadId(CrmVM.crm_id);
                        CrmVM.campaign_id = Data.campaign_id;
                        CrmVM.endorsement_id = Data.endorsement_id;
                        CrmVM.list_name = Data.list_name;
                    }
                    else
                    {
                        int id = 0;
                        //var _id = _db.crms.LastOrDefault();
                        //if (_id != null)
                        //    id = _id.crm_id;
                        CrmVM.crm_id = 0;
                        CrmVM.OnetId = "Onet" + id.ToString();
                        CrmVM.phone1 = mobile;
                        CrmVM.remarklist = new List<RemarkVM>();
                        CrmVM.activityHistoryList = new List<ActivityHistoryVM>();
                    }
                }
                return View(CrmVM);
            }
            else
            {
                Logger.WriteErrLog("Session Expired", String.Format("{0} ==> {1}", this.GetType().Name, MethodBase.GetCurrentMethod().Name));
                //Logger.WriteErrLog(, "CRM=>Index");
                return RedirectToAction("Index", "User");
            }
        }

        [HttpPost]
        public IActionResult Index(CRMVM model, string CommandName)
        {
            string url = "#";
            try
            {
                if (CommandName == "Add")
                {
                    UserVM _userModel = HttpContext.Session.GetObjectFromJson<UserVM>(RoleType.QA);
                    model.createdby = _userModel.user_id;
                    model.agent_id = _userModel.user_id;
                    model.createdon = DateTime.Now;
                    model.createdbyname = _userModel.user_fullname;
                    model.campaign_id = _userModel.campaign_id;
                    string endorser_name = _db.endorsers.FirstOrDefault(x => x.id == model.endorsement_id).endorser_name;
                    if (String.IsNullOrWhiteSpace(model.list_name))
                        model.list_name = String.Format("{0}{1}", endorser_name, DateTime.Now.ToString("ddMMMyyyyhhmmss"));

Onet_App/Views/CRM/CRMBucket.cshtml
@model Onet_App.Models.ViewModel.CRMVM
@{
    ViewData["Title"] = "CRMBucket";
    Onet_App.Models.ViewModel.UserVM _userModel = Context.Session.GetObjectFromJson<Onet_App.Models.ViewModel.UserVM>(Onet_App.Models.Services.RoleType.QA);
    if (_userModel == null)
    {
        Context.Response.Redirect(Url.Action("Login", "User"));
    }

    var role_name_text = _userModel == null ? "" : _userModel.role_name_text;

    if (role_name_text == Onet_App.Models.Services.RoleType.Agent)
    {
        Layout = "~/Views/Shared/_LayoutCRM.cshtml";
    }
}
<div class="modal fade" id="modalScheduleCall" tabindex="-1" role="dialog" data-keyboard="false" aria-labelledby="modalScheduleCallLabel">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" id="btnclosemodalScheduleCall" class="close" onclick="$('#modalScheduleCall').modal('toggle');" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Scheduled Call Back</h4>
            </div>
            <div class="modal-body">
                <div class="box box-primary">
                    <div class="box-body">
                        <table class="table table-striped with-border">
                            <thead>
                                <tr>
                                    <th>Account Name</th>
                                    <th>Account Number</th>
                                    <th>Address</th>
                                    <th>Schedule Date</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody id="tblScheduleCallBody">
                                @{

                                    if (Model.CallBackList.Count > 0 && Model.CallBackList != null)
                                    {
                                        foreach (var item in Model.CallBackList)
                                        {
                                            <tr>
                                                <td>@item.account_name</td>
                                                <td>@item.account_no</td>
                                                <td>@item.address</td>
                                                <td>@item.createdon</td>
                                                <td><a asp-controller="CRM" title="View Details" asp-action="Index" asp-route-mobile="@item.phone1" class="fa fa-eye"></a></td>
                                            </tr>
                                        }
                                    }

                                }

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
<section class="content">

    <form asp-controller="CRM" asp-action="CRMBucket" method="post">
        <div class="col-md-12">
            @{
                if (Model.role_name == Onet_App.Models.Services.RoleType.Supervisor)
                {
                    <div class="box box-primary">
                        <div class="box-header">
                            Filter Data
                        </div>
                        <div class="box-body">
                            <div class="col-md-5">
                                <div class="form-group">


                                    <label>Filter On the Basis Of</label>
                                    <select id="ddActivity" asp-for="filter_text" class="form-control" onchange="GetFilter(this.value);">
                                        <option value="0">--Select--</option>
                                        <option value="Last_Disposition">Last Disposition</option>
                                        <option value="Last_Updated_Date">Last Updated Date</option>
                                    </select>
                                </div>
                            </div>
                            <div id="Disposition" class="col-md-4">
                                <div class="form-group">
                                    <label><span style="color: #ff0000;">*</span>Callout Status Level 1: </label>
                                    <select id="ddcallout1" asp-for="callout_status_level1" asp-items="@(new SelectList(Model.dispositionModels, "disposition_id", "disposition_name"))" class="form-control "></select>
                                    <span asp-validation-for="callout_status_level1" class=" text-danger"></span>
                                </div>
                            </div>
                            <div id="Last_Updated_Date" class="col-md-4">
                                <div class="form-group">
                                    <label><span style="color: #ff0000;">*</span>Last Updated Date: </label>
                                    <input type="date" asp-for="filter_date" />
                                </div>
                            </div>

                            <div class="col-md-10">
                                <div class="form-group">
                                    <input type="submit" value="Filter" class="btn btn-primary btn-flat" />
                                    <input type="hidden" asp-for="_crmlst" />
                                </div>
                            </div>
                        </div>
                    </div>
                }
            }
            <div class="box box-primary" style="overflow:auto;">
                <div class="box-header with-border">
                    <span>CRM Details</span>
                    <div class="pull-right">
                        <!-- Button trigger modal -->
                        @{ if (Model.role_name == Onet_App.Models.Services.RoleType.Agent)
                            {
                                <a asp-controller="CRM" asp-action="LeadAssigment" class="btn btn-primary btn-flat" style="margin-left: 10px;">Get Data</a>
                            } }
                        <button type="button" class="btn btn-success btn-flat" id="btnScheduleCallBack">
                            Scheduled Callbacks
                        </button>
                    </div>
                </div>
                <div class="box-body">
                    <table class="table" id="tblexample">
                        <thead>
                            <tr>
                                <th>Contact Number</th>
                                <th>Account Name</th>
                                <th>Account Number</th>
                                <th>Call Out Status</th>

                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{
                                int i = 1;
                                if (Model._crmlst.Count > 0 && Model._crmlst != null)
                                {
                                    foreach (var item in Model._crmlst)
                                    {
                                        <tr>

                                            <td>@item.phone1</td>
                                            <td>@item.account_name</td>
                                            <td>@item.account_no</td>

                                            <td>@item.callout_status_level1_Text</td>

                                            <td>
                                                @*<a asp-controller="CRM" asp-action="Index" asp-route-mobile="@item.contact_number" class="fa fa-eye"></a> |*@ <a asp-controller="CRM" asp-action="Index" asp-route-mobile="@item.phone1" asp-route-isautomate="false" class="fa fa-pencil"></a>
                                            </td>
                                        </tr>
                                    }
                                    i = i + 1;
                                }
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </form>
</section>
@section Scripts
    {



    <script type="text/javascript">
        $(document).ready(function () {
            $('#tblexample').DataTable();
            $("#Disposition").hide();
            $("#Last_Updated_Date").hide();
            $("#btnScheduleCallBack").click(function () {
                $('#modalScheduleCall').modal('toggle');
            });
        });
        function CallBackLog()
        {
            $.ajax({
                type: 'GET',
                url: '@Url.Action("GetCallBackData", "crm")',
                data: { AgentName: CallLogId },
                success: function (data) {
                    if(data)
                    {

                        $('#modalScheduleCall').modal('toggle');
                    }
                    else
                    {
                        console.log("Something went wrong while Edit the Call Log. Please check the Log File");
                    }
                }
            });
        }
        function GetFilter(val) {
            if (val == "Last_Disposition") {

                $("#Disposition").show();
                $("#Last_Updated_Date").hide();
            }
            else {
                $("#Disposition").hide();
                $("#Last_Updated_Date").show();

            }
        }
    </script>

}

Onet_App/Views/CRM/CrmActivity.cshtml
@model Onet_App.Models.ViewModel.CRMVM
@{
    ViewData["Title"] = "CrmActivity";
}
<section class="content-header"></section>
@{
    if (TempData["Msg"] != null)
    {
        if (@TempData["Msg"].ToString().ToLower() != "error")
        {
            <div class="alert alert-info" id="MsgDiv1">
                <label>@TempData["Msg"]</label>
            </div>
        }
    }
}
<section class="content">
    <link href="~/datatables/dataTables.bootstrap.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.5.1/css/buttons.dataTables.min.css" />
    <form asp-controller="CRM" asp-action="CrmActivity" method="post">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <span>@ViewData["Title"]</span>
                    <div id="buttons" class="pull-right">

                    </div>
                </div>
                <div class="box-body">
                    <div class="form-group">
                        <asp:Label ID="lblMessage" Text="File uploaded successfully." runat="server" ForeColor="Green" Visible="false" />
                    </div>
                    <div class="col-md-12">
                        <div class="form-group col-lg-4">
                            <label>Choose Campaign Name: </label>
                            <select id="ddlcampaignName" asp-for="campaign_id" asp-items="@(new SelectList(Model.campaignlist, "campaign_id", "campaign_name"))" class="form-control"></select>
                        </div>
                        <div class="form-group col-lg-4">
                            <label>From Date: </label>
                            <input type="date" name="FromDate" class="form-control" />
                        </div>
                        <div class="form-group col-lg-4">
                            <label>TO Date: </label>
                            <input type="date" name="TODate" class="form-control" />
                        </div>

                        <div class="form-group">
                            <input type="submit" class="btn btn-success btn-flat" id="btnSubmit" name="CommandName" value="Submit" />
                        </div>
                    </div>
                    <div class="col-md-10">
                        <div class="box-header with-border">
                            <span>CRMActivity Download Details</span>
                        </div>
                        <div class="box-body">
                            <table id="tblData" class="table table-striped">
                                <thead>
                                    <tr>
                                        <th>Activity Name</th>
                                        <th>Status</th>
                                        <th>Summary</th>
                                        <th>Time Stamp</th>
                                        <th>Phone 1</th>
                                        <th>Phone 2</th>
                                        <th>Phone 3</th>

                                    </tr>
                                </thead>
                                <tbody>
                                    @{
                                        int i = 1;
                                        foreach (var item in Model.CrmActivitylst)
                                        {
                                            <tr>
                                                <td>@item.activity_name</td>
                                                <td>@item.status</td>
                                                <td>@item.summary</td>
                                                <td>@item.time_stamp</td>
                                                <td>@item.phone1</td>
                                                <td>@item.phone2</td>
                                                <td>@item.phone3</td>
                                            </tr>
                                        }
                                        i = i + 1;
                                    }
                                </tbody>
                            </table>
                            <div style="display:none">
                                <table id="tblDataAll" class="table table-striped">
                                    <thead>
                                        <tr>
                                            <th>Activity Name</th>
                                            <th>Status</th>
                                            <th>Summary</th>
                                            <th>Time Stamp</th>
                                            <th>Phone 1</th>
                                            <th>Phone 2</th>
                                            <th>Phone 3</th>

                                        </tr>
                                    </thead>
                                    <tbody>
                                        @{
                                             i = 1;
                                            foreach (var item in Model.CrmActivitylst)
                                            {
                                                <tr>
                                                    <td>@item.activity_name</td>
                                                    <td>@item.status</td>
                                                    <td>@item.summary</td>
                                                    <td>@item.time_stamp</td>
                                                    <td>@item.phone1</td>
                                                    <td>@item.phone2</td>
                                                    <td>@item.phone3</td>
                                                </tr>
                                            }
                                            i = i + 1;
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</section>

@section Scripts{
    <script src="~/datatables/jquery.dataTables.js"></script>
    <script src="~/datatables/dataTables.bootstrap.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.1/js/dataTables.buttons.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.1/js/buttons.html5.min.js"></script>
    <script>
        $(document).ready(function () {
            setTimeout(function () {
                $("#MsgDiv").fadeOut('fast');
            }, 5000)
            $("#tblData").DataTable();
            var Lead = $("#tblDataAll").DataTable();
            var buttons = new $.fn.dataTable.Buttons(Lead, {
                buttons: [
                    {
                        extend: 'excelHtml5',
                        text: 'Download'
                    }
                ]
            }).container().appendTo($('#buttons'));
        });
    </script>
}

Onet_App/Views/CRM/LeadUpload.cshtml
@model Onet_App.Models.ViewModel.CRMVM
@{
    ViewData["Title"] = "LeadUpload";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<form asp-controller="CRM" asp-action="LeadUpload" method="post" enctype="multipart/form-data">
    <section class="content-header">
        <h1>Lead Upload</h1>
    </section>
    @{
        if (TempData["Msg"] != null)
        {
            if (@TempData["Msg"].ToString().ToLower() != "error")
            {
                <div class="alert alert-info" id="MsgDiv1">
                    <label>@TempData["Msg"]</label>
                </div>
            }
        }
    }

    <section class="content">
        <div class="col-md-8">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <div class="col-md-12">
                        <label>Enable Get Lead Functionality </label>
                        <input type="checkbox" asp-for="enable_get_lead" />

                        <input type="submit" class="btn btn-success btn-flat pull-right" id="btnSubmit" name="CommandName" value="Get Format" />
                    </div>
                    <div class="box-body">

                        <div class="col-md-4">
                            <div class="form-group">
                                <label><span style="color: #ff0000;">*</span>Choose Campaign Name: </label>
                                <select id="ddlcampaignName" asp-for="campaign_id" asp-items="@(new SelectList(Model.campaignlist, "campaign_id", "campaign_name"))" class="form-control" onchange="GetEndorser(this);"><option value="0">--Select--</option></select>

                            </div>
                        </div>
                        <div id="ddlEndorser" class="col-md-3">
                            <div class="form-group">
                                <label>Endorsed By: </label>
                                <select id="endorsername" asp-for="endorsement_id" asp-items="@(new SelectList(Model.EndorserModelList, "id", "endorser_name"))" class="form-control" onchange="GetListName(this.value);"><option value="0">--Select--</option></select>

                            </div>
                        </div>
                        <div id="txtListName" class="col-md-5">
                            <div class="form-group">
                                <label>List Name: </label>

                                <input class="form-control" type="text" id="listname" asp-for="list_name" />
                                <span asp-validation-for="list_name"></span>
                            </div>
                        </div>



                        <div class="col-md-10">
                            <div class="form-group">
                                <input type="file" name="postedFile" id="postedFile" /><br />
                                <input type="submit" Text="Upload" class="btn btn-primary btn-flat" name="CommandName" value="Upload" />

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</form>
@section Scripts{
    <script>
        $(document).ready(function () {
            setTimeout(function () {
                $("#MsgDiv").fadeOut('fast');
            }, 5000)
            $("#txtListName").hide();
        });
        function GetEndorser(a) {
           var strUser = a.options[a.selectedIndex].value;
            var html = "<option value='0'>--Select--</option>";
               $.ajax({
                type: 'POST',
                url: '@Url.Action("GetEndorserName", "CRM")',
                data: { Id: strUser },
                success: function(data) {
                    if (data.length>0) {
                        $.each(data, function (key, value) {
                            html += "<option value=" + value.id + ">" + value.endorser_name + "</option>";
                        });
                        $("#endorsername").html(html);
                    }
                 }
            });
        };

          function GetListName(a) {
              $("#listname").val("");
              $.ajax({
                type: 'POST',
                url: '@Url.Action("GetListNameTxt", "CRM")',
                data: { id: a},
                  success: function (data) {
                      console.log(data);
                      $("#listname").val(data);
                      $("#txtListName").show();

                }
                });
        }
    </script>
}